### ISSUE TITLE
@reactiveComponent seems to cause, "Cannot call a class as a function".

### ISSUE THREAD

**Issue by dschalk** [mweststrate/mobservable#29] opened 2015-09-18 20:20 UTC
Running webpack on the file named B2.jsx produced a well-functioning bundle.js file until a few days ago.     Now, @reactiveComponent seems to be causing browsers to crash, reporting:
[mobservable.view '[m#1]'] Caught error during computation: TypeError: Cannot call a class as a function at classCallCheck (http://localhost:3000/bundle.js:64:100) at B2 (http://localhost:3000/bundle.js:85:6) at t.createClass.render ...

All of the code, along with the complete error message, is at  [https://github.com/dschalk/cow](https://github.com/dschalk/cow). This is B2.jsx:

 ```javascript
 'use strict'
 import React from'react';
 import mobservable from 'mobservable';
 import {reactiveComponent} from 'mobservable-react';
 export {B2};

 // @reactiveComponent class B2 extends React.Component {
 class B2 extends React.Component {
   constructor(props) {
     super(props);
   }
   render = () => {
   return (
     <div> <h1>Cow</h1> </div>
   )}
 }
 React.render(<B2 key='B2' />, document.getElementById('divSix'))
 ```
As you see, the last thing I did to make it work was to comment out @reactiveComponent.

**Comment by dschalk** [comment] 2015-09-18 21:06
I cloned [https://github.com/dschalk/websockets-react]([https://github.com/dschalk/websockets-react), ran "npm install" and then "webpack". This used to cause the game of Score to run in browsers, but now I get:
[mobservable.value '.Sbackground'] It is not allowed to change the state during the computation of a reactive view. (stack size is 2, active view: "ComputedObservable[.groupWatch:undefined] function groupWatch() ... It still works with the "bundle.js" file that comes with the clone, which was made three weeks ago.

I didn't use @reactiveComponent. Instead, I defined my main function as B2X and at the end of the file, I ran:
```javascript
let B2 = mobservable.reactiveComponent(B2X);
React.render(<B2 key='B2' />, document.getElementById('divSix'));
```
I was showcasing the usefulness of Mobservable. Now, all of the code I published results only in error messages. Did Mobservable updates break my apps? If so, what can I do to make them work again. If not, any helpful hints would be much appreciated. I don't understand this.

**Comment by mweststrate** [comment] 2015-09-18 21:39
Hi David, 

I'm sorry you run into trouble suddenly when compiling! Concerning the decorator, afaik nothing has changed on my side that could break this. But you could see whether the following downgrades fix your issue:
* mobservable@0.1.5 instead of 0.1.6
* use babel@5.8.23 or 5.8.22

In general, I recommend to not use `latest` in your package json, but always specify the version you tested against, to avoid being surprised at inconvenient moments.

---

Concerning the second issue (it is not allowed to change the state), I noticed that I was not enforcing the mental model of Mobservable I had initially in mind. So since `0.6.6` I now log the errors you mentioned to pinpoint the mismatches. Although the actual behavior should not have changed yet. 

The mental model behind it is this: all reactive stuff is either `state` *or* `views` that are derived from the state. As soon as view functions start to change the `state` this mental model is broken. Technically it will still work (atm) but basically the view functions now have become impure functions that have side effects on the state. This makes it hard to reason about them and might easily result in unending loops. 

I took a short look at your code, I think the issue lies in line 651 of B2.jsx: the `groupwatch` function is made reactive because it is part of the object that is passed through `makeReactive` (on line 636).
However, it looks like `groupwatch` isn't a _view_ that is derived _from_ the state, but an _action_ that is applied _to_ the state. If you move the `groupWatch` function out the initial object, and simply assign it to `data.groupWatch = function() { .... ` right after the `makeReactive` call, this issue is probably fixed.
makeReactive assumes that all functions you pass into it are views, not actions.

I wrote recently a lot more about the concepts of _state_, _views_ and _actions_ in the documentation: http://mweststrate.github.io/mobservable/intro/concepts.html

I hope these pointers help you out! Otherwise I'll try to find some time tomorrow to take a closer look. 

Regards,

Michel

**Comment by dschalk** [comment] 2015-09-19 17:37
Update
I found an old working version of mobservable-monads. I removed the 'package.json' file and ran 'npm init'. I removed the 'node_modules' directory and ran 'npm install'. Then I ran 'webpack' and 'warp' and refreshed 'localhost:3000'. I got the same error messages I have been getting for the past week,  

I replaced 'node_modules' with the earlier version, ran 'webpack' and 'warp', and the app worked just as before in the browser. 

I thought running 'npm init', removing 'node_modules', and running npm install would result in a 'node_modules' directory identical to the first one. It appears that I was wrong about that. The attached screen shot shows what I got by running 'npm init' on the newly generated 'node_modules' directory.

![compare_package json_files](https://cloud.githubusercontent.com/assets/2214003/9977323/97f21004-5ed0-11e5-9d47-23f97c82a1a6.png)

If this is how the Node Package Manager works, then I can't share my experiments on Github by just providing a 'package.json' file. I have to push the whole 'node_modules' directory so people can modify the code and create a working 'bundle.js' file by entering 'webpack' in their terminals.  I wonder if Bower can do better than this.

**Comment by mweststrate** [comment] 2015-09-19 18:07
Hi David,

I've just checked out your `cow` repo and reproduced the issue. The classes generated by babel where somehow different from the classed generated by babel I tested with. Not sure where the difference comes from, but I could easily fix it, so using `mobservable-react@0.1.7` should fix the issue. 

It is not necessary to commit `node_modules` to get, as long as you specify exact version numbers (e.g. `"mobservable": "0.6.9"`, without caret) all cloners should receive exactly the same packages after an npm *`install`*.

**Comment by dschalk** [comment] 2015-09-19 20:17
Many thanks. I didn't realize that I needed to delete the carets after running npm init. I should have looked up 'carets' in the npm documentation the first time I saw them in my package.json file.

I cloned mobservable-monads and ran 'npm install' using the package.json file with 'latest' next to all of the dependencies. Today it worked. I removed 'package.json, ran 'npm init', deleted the carets, removed node_modules, ran 'npm install', 'webpack', and 'warp' and verified that it worked perfectly. I pushed the project, cloned it, ran 'npm install just to make sure. It performs as intended. 

I tried the same with mobservable-react-buttons. It didn't work, so deleted 'package.json' and replaced it with the one from mobservable-monads. The fully functional app is here on Github in the dschalk/mobservable-react-buttons repo.

Here is a screen shot of the file that works.
![working_dependencies](https://cloud.githubusercontent.com/assets/2214003/9977929/72a6f690-5ee7-11e5-9715-152f0e9665e5.png)

**Comment by mweststrate** [comment] 2015-09-19 21:06
Cool, so all build issues are solved? Did you also see my other note on the non-pure views in B2.jsx? I guess you will like the idea of pure views only given the haskell background ;-).

**Comment by dschalk** [comment] 2015-09-19 22:26
Very impressive! I was thinking of using my generilyzed monad creations to insure sychronysity - sort of a substitute for chains of promises - but there seems to be no need for such a thing, You apparently have synchronous chains of events covered. 

I tried the link to the introduction at the end of "Concepts and Principles". It is broken. "http://mweststrate.github.io/mobservable/intro/" displays a "404" page.

**Comment by mweststrate** [comment] 2015-09-20 18:19
Thanks for reporting, I'll fix the link.

**Closed by mweststrate** 2015-09-20 18:19 UTC
