### ISSUE TITLE
My Small test

### ISSUE THREAD

**Issue by mehdi-cit** [mweststrate/mobservable#22] opened 2015-08-24 08:42 UTC
Hello everyone,

I really like Mobservable and I'm investigating whether I can use it for the scenario described below.
I want to declaratively "sync" between several objects. For instance, having three object X, Y and Z. I want to declare how those 3 "relate" to each other. So instead of triggering callbacks when one of these objects changes to update/sync the other two. I simply have the declaration dictate how the syncing must be performed.

To this end I did some tests like the one below. where two object (both having the same exact structure for this simple test) must be totally in sync (their variables must have the same values). If one changes any of the two variables the other one would automatically have the same value(s).

The idea is to have both objects totally independent from each other. The responsibility of doing the sync relies on a third system (some kind of broker).  

Note that I'm using the global namespace (i.e. window) so as to be able to test this in chrome devtools (in the console)

```
var mobservable = require('mobservable');

window.wareHouse  = mobservable.makeReactive({ stock:0, price:5 });
window.shop           = mobservable.makeReactive({ stock:0, price:5 });

window.setSP = function(x, newStock, newPrice){ x.stock = newStock; x.price= newPrice;}  

function display(name){
  console.log('Total ['+name+'] =>>>>> '+window[name].price*window[name].stock); 
}

mobservable.sideEffect(function() {
  display('wareHouse');
});

mobservable.sideEffect(function() {
  display('shop');
});

mobservable.sideEffect(function() {
  console.log('wareHouse <- shop ')
  window.wareHouse.stock = window.shop.stock; 
});

mobservable.sideEffect(function() {
  console.log('shop <- wareHouse');
  window.shop.stock = window.wareHouse.stock; 
});

mobservable.sideEffect(function() {
  console.log('wareHouse <- shop ')
  window.wareHouse.price = window.shop.price; 
});

mobservable.sideEffect(function() {
  console.log('shop <- wareHouse');
  window.shop.price = window.wareHouse.price; 
});
```
When the code above is loaded into the browser (using chrome). I hit F12 and perform the 'tests' below. One line at a time and observe the output on the console to understand what's happening.
Remember, one line at a time.
```
window.setSP(window.wareHouse, 2, 7);
window.setSP(window.wareHouse, 5, 6);
window.setSP(window.wareHouse, 1, 2);
```

It basically works. I wonder however if it is possible with Mobservable to make it in such a way that we only have the minimum number of operations. Can we use the fact that the updating in setSP happens atomically on both variables at once to improve this ? (we'r having the syncing triggered for each variable within the setSP function. Could we have it 'trigger' just once? )

PS: I tried to group the functions inside sideEffect (syncing on both variables as the same sideEffect) but it did not work

**Comment by mweststrate** [comment] 2015-08-24 09:08
Interesting case!
I'll try to dive into it more deeper later today, but at least in the setSP function you should be able to do

```javascript
mobservable.transaction(funtion() {
    x.stock = newStock;
    x.price = newPrice;
});
```

**Comment by mehdi-cit** [comment] 2015-08-24 09:11
Wonderful. It is working:
```
window.setSP = function(x, newStock, newPrice){ 
  mobservable.transaction(function() {
    x.stock = newStock;
    x.price = newPrice;
  });
}  
```

**Comment by mweststrate** [comment] 2015-08-24 09:38
Now that I think of this, this is exactly one of the situations a had on my todo list to forbid :-P. 

The problem is that the side effects are not pure; they are updating the state their own execution depends on. In this case it works, but in more complex situations it can easily become hard to reason about and error prone; for examples, if the code would contain `x.price = newPrice + 1`, it would probably start to loop. Also it is harder to optimize.

A clean way to solve this would have a central stock and price state, and just derive he others from it:

```
centralState = mobservable.makeReactive({
  stock: 0,
  price: 5
});

wareHouse = mobservable.makeReactive({
  stock: function() {
    return centralState.stock
  },
  price: function() {
    return centralState.price
  },
  setStock(newStock) {
    centralState.stock = newStock;
  },
  setPrice(newPrice) {
    centralState.price = newPrice;
  }
});
```

That would completely avoid the need for the side effects. The set functions can probably be turned into ES5 setter for more convenient invocation.

But it depends on your use case whether you want to have such a central state. Would the above solution suffice for you? If you are creating a distributed system, the original solution makes sense and will work (and keep working), because it turns the problem in an asynchronous problem. But again beware of unending loops in such case. But within a single process, data should either be derived data, or mutable state, but not both at the same time. Just to ease the mental model of your state.

Does that make sense? Just curious about your use case!

**Comment by mehdi-cit** [comment] 2015-08-24 10:57
Thanks. 

I thought of the 'loop' problem and I'm fine with it (it could happen if the syncing between objects does some rounding so that the "declared equivalence" between the objects will never be 100% met).
Is there any other potential problem in the above approach? 

I thought of having a 'star topology' but the former is more liberal/general. Furthermore, to the best of my understanding the code you provided above still need something like 'mobservable.transaction' to avoid triggering changes more then the "absolute minimum number of times". Also, wareHouse is aware of the centralState. 

In the best of the worlds. I'd have objects that are totally unaware of each other and all syncing happens with the help of an "external broker" in the minimum number of steps :8ball:.

**Comment by mweststrate** [comment] 2015-08-27 06:32
Yeah I can definitely see your use-case. I think the safest way to protect against looping is to update a version number upon change or distribution, and check whether your already up-to date before applying changes.

I'll close the issue for now, but don't hesitate to comment if new issues arise.

**Closed by mweststrate** 2015-08-27 06:32 UTC

**Comment by mehdi-cit** [comment] 2015-08-27 22:00
One last comment if you will. Should I conclude that the approach I've chosen is good to go?
PS: Indeed I will have to use versioning to avoid extra steps or even infinite loops.

**Comment by mweststrate** [comment] 2015-08-28 07:29
Yes, this a valid approach for a distributed system :) For just local
system I think it is recommendable to stay with 'one truth'.
