### ISSUE TITLE
Unexpected React warning concerning `forceUpdate` in combination with `jspm-hot-reloader`

### ISSUE THREAD

**Issue by capaj** [mweststrate/mobservable#47] opened 2015-11-11 16:03 UTC
```
Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the InputWithCheckmark component
```

I am developing with [jspm-hot-reloader](https://github.com/capaj/jspm-hot-reloader) and it seems like when my app rerenders, you still hold references to components which were replaced by the new global rerender. 

Why aren't you hooked into componentWillUnmount on the component and call `disposer()` there?

**Comment by mweststrate** [comment] 2015-11-11 17:49
Hi @capaj 

We use the webpack react hotloader without similar issues. As you can see [here](https://github.com/mweststrate/mobservable-react/blob/master/index.js#L91) the disposer is actually called in componentWillUnmount. 

Can you verifiy that `@observer` is the most inner decorator of the component? Can you also share the versions of the relevant dependencies or maybe the source of your test project? 

I'm wondering whether the component tree gets unmounted at all if you trigger a global rerender, because I would expect that a global `React.render` on the same node will keep the old instances (based on the old component definitions) intact in most cases due to the reconciliation mechanism; if a component returns `false` on its `componentShouldUpdate` it's children won't be re-instantiated and thus be instances of 'old' types?

**Comment by mweststrate** [comment] 2015-11-19 21:53
Hi @capaj 

Is this still an issue? If so, can it be reproduced somewhere?

Tnx!

**Comment by ikido** [comment] 2015-11-29 07:43
@mweststrate I've stumbled on the same issue though I'm using webpack + react hotloader. Making @observer the topmost decorator fixed the issue for me, thanks for the suggestion!

P.S. Thank you for this awesome lib, Michel! The more I'm working with it the more I love it. Really strange that it haven't got much traction, probably due to not 'canonical' and advertised Flux way of feeding data for React.

**Comment by capaj** [comment] 2015-11-29 11:05
@mwestrate will build a showcase project when I've got time. Probably few weeks. 😕

**Comment by mweststrate** [comment] 2015-12-01 11:00
@ikido thanks!

@capaj that would be awesome :)

**Comment by mweststrate** [comment] 2015-12-15 19:08
@capaj I assume this issue has been solved now?

**Comment by mweststrate** [comment] 2015-12-18 14:12
forceUpdate error might be a duplicate of: https://github.com/mweststrate/mobservable-react/issues/12

**Comment by mweststrate** [comment] 2015-12-18 18:24
If this issue wasn't already resolved, version 2.1.1 probably will :)

**Comment by capaj** [comment] 2015-12-18 18:33
@mweststrate will try it out

**Closed** 2015-12-28 14:09 UTC

**Comment by capaj** [comment] 2015-12-28 15:49
@mweststrate I haven't seen it anymore, thanks for the fix
